#.travis.yml

sudo: required
dist: trusty
language: node_js
node_js:
  - "9"

cache:
  yarn: true
  directories:
      - ./node_modules

branches:
  only:
    - master
addons:
  chrome: stable

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng build --prod

after_success:
  - ng lint
  - ng test --single-run --browsers ChromeTravisCi

notifications:
  email:
    on_failure: change
    on_success: change
