#.travis.yml

sudo: required
dist: trusty
language: node_js
node_js:
  - "9"

cache:
  yarn: true
  directories:
      - "node_modules"

branches:
  only:
    - master

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod

test:
  - ng test --single-run --no-progress --browsers ChromeHeadlessNoSandbox

notifications:
  email:
    on_failure: change
    on_success: change
